# note: this file is changed automatically as part of the `shellbin` dev pipeline.
# see https://github.com/england2/.github/workflows/build-containers.yml
global:
  DBADDR: shellbin-mysql.shellbin.svc.cluster.local
  DBSERVICEADDR: db-service.shellbin.svc.cluster.local
  PUBLIC_SERVER_ADDER: placeholder.net
  registryUrl: ghcr.io/england2/shellbin
  imagePullSecret: ghcr-secret
webserver:
  replicaCount: 1
  name: webserver
  image:
    repository: ghcr.io/england2/shellbin
    pullPolicy: IfNotPresent
    tag: webserver-c4b2d5f3b6afc0c28dab601b001d64a9bea2a3c4
dbservice:
  replicaCount: 1
  name: db-service
  image:
    repository: ghcr.io/england2/shellbin
    pullPolicy: IfNotPresent
    tag: dbservice-c4b2d5f3b6afc0c28dab601b001d64a9bea2a3c4
ncserver:
  replicaCount: 1
  name: ncserver
  image:
    repository: ghcr.io/england2/shellbin
    pullPolicy: IfNotPresent
    tag: ncserver-c4b2d5f3b6afc0c28dab601b001d64a9bea2a3c4
