# note: this file is changed automatically as part of the `shellbin` dev pipeline.
# see https://github.com/england2/shellbin/blob/master/.github/workflows/pipeline.yml
global:
  DBADDR: shellbin-mysql.shellbin.svc.cluster.local
  DBSERVICEADDR: db-service.shellbin.svc.cluster.local
  PUBLIC_SERVER_ADDER: placeholder.net
  registryUrl: ghcr.io/england2/shellbin
  imagePullSecret: ghcr-secret
webserver:
  replicaCount: 1
  name: webserver
  image:
    repository: ghcr.io/england2/shellbin
    pullPolicy: IfNotPresent
    tag: webserver-c84c58d0a4cd4d04c92604e6305f3c96c1cd1e92
dbservice:
  replicaCount: 1
  name: db-service
  image:
    repository: ghcr.io/england2/shellbin
    pullPolicy: IfNotPresent
    tag: dbservice-c84c58d0a4cd4d04c92604e6305f3c96c1cd1e92
ncserver:
  replicaCount: 1
  name: ncserver
  image:
    repository: ghcr.io/england2/shellbin
    pullPolicy: IfNotPresent
    tag: ncserver-c84c58d0a4cd4d04c92604e6305f3c96c1cd1e92
