apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shellbin
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: shellbin
  sources:
    - repoURL: git@github.com:england2/shellbin.git
      targetRevision: master
      # `path: helm` refers to the `helm` folder in england2/shellbin
      path: helm
      helm:
        releaseName: shellbin
        valueFiles:
          - argocd-reconciled-yaml/cluster-yaml/applications-argocd-config/application-shellbin.yml
    - repoURL: git@github.com:england2/cluster-repo.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
