---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: webterm
spec:
  encryptedData:
    .dockerconfigjson: AgAUe0MdYADhREXxisEOQXA5Tu14w3MYVBYWO+ju4j01PMF2KVkvuh1laQM/VrbNONo0U1ysGVRq/Y5ZPjepocQS8zZIsdwQyFhYSKRKYOwKxxIoWu1fAryVUbXhZAgs9yJ2C11gi6Cyxouy4jB03XPcBQYtbG22HGkitROzNb3PLzJiDYiF8IXcrmDSGBUF9qrvjqh3y9fhBWSaDSt5c6/MgT1Jr3jdzRrGvzu70cHi+p9tbulOjulS42q8qoUBGZDrYKFSIEzF0XIsDfb0w28BTY36LwzAY0d3Vxoc0Z6bNs5M867KdFfUDRGegxS9nis/M1EcV11GmeZdcs0amsCEmsNKZ5BPCeUPflNsPmetVjO/44JKLOvXCLTLNmtBFF3juYOXNsZkJBwpR7Aju7Uce/aej1osRMDY7elypYkxHB8sq+HRGTz28xnpHftGrbQIbAh8E2kqp1uVTMUy8XVNCjqVUhi07jMFagb4iW3Y1fNpxhqamSC31M7j4YyK98BZBIoiCOwF+WPNX3Ye5XPfnBTk/vCZ/mpOl69mli41BIwtJqx5gqFWcTF1B2aMH68sPCDq1wHpprHA3UPaog2CXe/d25tIb6pEWdmqaor+O8x6v9jBYb8KCshkYM38gISt4T8Gd7jx4D3lt0gkCQUOAQhgaql6HkB+wc/jcgGDJ0omUTDvsONum0lC/D4qI/uMxppo7+VNLg3gf8kG8PvXCQ73WMMRVqCI/6iA1LPJxYP5EowH+mQ5PveW6zPI9dIOHF+BeScQDOkKrDvmq/LdnCbH+avkbZkNonnz899JSKWZmxDRBWdsSCYW0oiBfG0qZAvVDaWjttox0bceMyzVWdfu9q2F0zttoia+yjIdlUA=
  template:
    metadata:
      name: ghcr-secret
      namespace: webterm
    type: kubernetes.io/dockerconfigjson
