---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: webterm
spec:
  encryptedData:
    .dockerconfigjson: AgChaHI9v9ZjVNCuOVO143Mie8M2SEvUpm1oLVIXhn1MLL7SNdN4qAb9fv9fdbJf/fpdxBthvfrzUjqCwZGq8Jekiln7rolZi3iHn9nNBH9iAzqgFt7cXgPho7nKlV9O02kkrjg/kwUpfGMAEcHh30vAgHjnQTURKqFI/jGt3BFyIFKNHaXU9iJw1RZPoI2L6JzYh4z4glXh7T6nZODMBQ+I8w2hUnz/DduTG7c8KEpliUD5XxDkeJCkN+Atr4p/pTEiamlbJVbWh9fEjcw4QwiEqZGXWn1IEQ1z61glErlYAyECO2i5Gu6FCArgxFhcPJZhxaJ66mEDnA+eecNFM7+Rk2vZexaBia3mobo8LxDwbL6BIuBTDaJVXt+wh5EHM5I5i3fcKcaO/ihp4isYmwUphAtGM7I3iG7cJpuQU0GQaRJXnQSdscltJ5kkbnhTKyZuCCnXVzyLWEe+KB5hat3DUPexupWRCQZRy/Qgy+lhA1kmWxQUulADLTBdikX7VUfZvKGRrPBsCz6duBh+WrZ+NvtM7wIlFzZjF8tpJ4xZzNqp0iqgBLczPLs90KDJF4yuybTqRL98FPq5rZ5Kq7iz0Km1XRCICokRshBTTuoqp3XqqFpmW2CcnxvtftfOXZGGQq/sVwuBssDmex6GHtlRKBALRL/yZIfLsBUCLs9NhfVoICyDkjfvFTdzdHjFG7C9cwwtInG76ZqFhu/j2AfqOIycMUGFQ8K3oai6ir5QedS5UNrCflzL23PdawCLVGi7hbk2m02lDjp4RYrI6k5UheTcjbSyoXbzwODBXs6Icw7cXfbwXbKJRNpaW03ZmseZGUsIyHtIG/O5aASb5E0wfP3xhJF2JiziYw75W1XRhhX/rbTeVArGFVwHOnVrWWuD3kDXgflT60FznpZ/mP9x2rMsWU7pEfuRmshP3K53VwXJOk+4uzRmXcSBdkXKMy9P2/Zh4w/qzWdz7hQQwXubcvHKnyAi8OZjwXEM+4dMOHdueMj9eiOTyu3jjLgwGFkPexfhZaO+08KRZ1mUVwTSr2cNkNuGhY181Q==
  template:
    metadata:
      name: ghcr-secret
      namespace: webterm
    type: kubernetes.io/dockerconfigjson
