apiVersion: v1
kind: Pod
metadata:
  name: ghcr-test
  namespace: ghcr-test
  labels:
    app: ghcr-test
spec:
  containers:
    - name: ghcr-test
      image: ghcr.io/england2/cluster-repo:service1
      ports:
        - containerPort: 4872
  imagePullSecrets:
    - name: ghcr-secret
