apiVersion: v1
kind: Service
metadata:
  name: ghcr-test-svc
  namespace: ghcr-test
spec:
  type: NodePort
  selector:
    app: ghcr-test
  ports:
    - port: 80
      targetPort: 4872
      nodePort: 30080
