---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: shellbin
spec:
  encryptedData:
    .dockerconfigjson: AgB3oUfS/r92SYUYBXERuIAzQrsbM/TmniOJZ6u13TDjeWTSUNzbzJ1R1XbJ3ZxPjbAzP4is2p4+smtRu34M83H8+A2wftcWiG3yXDt1sBG7SIe8gnpeFqsWHhZnDcze768brJw286uaP9o+eSCZ0Wdfyg/C/Nn/+meg9E6snRcN37zDYyJUOn1VJ+MvY2w+RMrXoLKCVstF60fs6z6zD/rZFZ2kFSHESOnQkpCV6JkDmbBDueCp0Iwjp5vNoazvQ/HRbLvYc1pWbeSodRi+HR5om0uD04HN4NlRHL3q3mwjCWevbvXynbXY57XY7nr8xSldSEGhW1ESiPL+ZJtUfpqbEXQsZmOh08r/cqDFN7A/qSyzcNzCSm26zzuY5QvEaunuHG1yM0AoEQodmOMeU4KIwUSnaolNUfUJarp+1tj6smArwEDQoqLR41NluPmf7NJnTHJbvGXDNs+yGcYaqoTvo1JllObrUB33K+inaXr1w8xgwm1QlLOBF1/76oKMwQ+Up6nspVuWPMCLUUNZ+bTXTjQAl9uhQWA+w1ORqR7UFsj6dQmi8U5HlQbKuUm9+PsGlka88LfuGyKFS7WdJj+5KhgBtuIkTXULNINsSsGTgB8WJp74b1TfOF9ks2g8bLLonpjNXY07DQsQqZrhFimeSE9h5akWNnHThTOkOt35Wh2lDN21EOadISeEizfmclK8KPGRR/1aaIisygbVIOL9QofdMKO2BTV7KIAOb8f+53crO4iuXELxgWWSsCzkwIfCy7F5BEegeLzf3sO4s37p8wFiCM//Qi4j7me2Me3vrcizVrPZFo1FKaXDSV2zW5+5D5+dxvhl+UjwtTeUs6+X9I1YUvJvzPyWyBTfP/vThXI=
  template:
    metadata:
      name: ghcr-secret
      namespace: shellbin
    type: kubernetes.io/dockerconfigjson
