---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: shellbin
spec:
  encryptedData:
    .dockerconfigjson: AgCHWZSEjydIRKST+YAf4FSSGuiH3THGpotvq1tiUBg0rjYdGVIF8M9bZzuXsV64OsSy7QVug/5cHdis8wLkiBgmrlusXijasx2Mf87teislSyX+8DRx0AVmGVaoQgXRXEdv8aZCMU7sm1SlFXAbq7JIpivo9WrOHRqxSNv+lN02u5mDm9mTPH6AUyc4odakZN/xgZQsvDIlDeL3fMGF5ITmJ/Lp/ukRR4MV5r1ku83pbBchGLGI86wIQdJK7A58Fr5LpCrIsrx5fSJc3I58TZRm8hW4jE8t1RTBElhMx65ggNrRgFqPkDxuxEDOJWhhvCCzE6zl0OdtMGt4sK+TYSz4esJgz9NpGJNlbMl6v0qoUy5dRfUheS0TOwfSFR26/6wIRF/8feGq/AxgExMPPxhnrus7vjDTEPwqRPNtfLaaWURLflR4XXvWNK2ujZDTgC3qa78Rk77f7QyD8/T1Ylf/QwzNXnYLozFpsMQM68uMP6xDaCOb2aep1ZH/fG++ZGg6Kl3KR7fThi6IskvCsbpM5v/BY2uMaTIAvxRz4rRnEnlvtv0cdESVu1IIDLEv85GEuz+NWQNmwEhoJrZHOn08q8bD6zqkZYCeFKgq3YKHH+WSrfBm8xsfnDPLiKGQxaGDFbQGsMKdzc2FZEfHp4bYtej3nE4515MnWgppacGzX8sl9pEqst0tIRk7fpAAngYsrtnEFwEdz+V8mrboYyihJCVYZIu673qaPoQdlDzqEMlngMONvdZcCGi2B7qw8ai7qKvtsLwTmxJEsTeHwPzfltps1WxsvzR/nMyKC7U+++MgzVMnU94dfeSERxm5L0LX5IAM0FPdT+cE1AhOgJCqZCSMLRR/hqo0Asx74NkXvPNxMlqSmSdfBPGhSMjWv+VECOI3+dBF9BiHjS1/5uiDmKTnirBHZZUNDAru9+sulVkjyr36g0r+ngfZdW8Hw0Lm8QYbrg1I9QueRzJh9PMJNrYX1jUSLxyjYp7B21Q5rdvhI94MTb4eFOk0Mxfpr/zRAYwA7cV1Qg1efZjj9FE1Wzr1apzZ3wEOgQ==
  template:
    metadata:
      name: ghcr-secret
      namespace: shellbin
    type: kubernetes.io/dockerconfigjson
