---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret-shellbin
  namespace: shellbin
spec:
  encryptedData:
    .dockerconfigjson: AgCXkx80k+aQ4HKkex9NBggOTWeA/PPyJ6r6YVI0iv91pcWpjG/op5QqFYEUpGA+szGQO2OmhkBEEHteKbu3Xxb/TaaV/YuYim7OsiOfAhkjyXHb6RDXtCviuvHG8hfY4dgUKY1H9TLhyM1lkZFcf7yjt2w5V938hly3C3YMyfKdvCFS7xW8FG/7JI5txnydII55jCV3Zs+CCL8APB+4EBk6HPcQYSRppGqTISxHUG6DVp6SrF/UDFRqbXvkB7rIcd47Sg22b3uIY1UGUyn6Q2v4D77EczkIF+t+tVlN4PTgJ95PA+s6R6PUDPhiucv+2B1ovCqRBxV2NDdQFPeL0vIyIwMfdgbstcpCOn8SAg+l1xHjPMPjh1LHluYImKUSRLUm/h+NHACr7SZ4HUO3Dli9GcOc9RGadbHKxoRA7VPJrcsfH0rx2ncWTTeIL3IRLKxr9Xk+s4ZEQRWWJ9k4McescgyDHDT2apVTActUhooWMpz2FzrnzpYmKeczjD8l+rIoIWMTooAIU2MKT1PJ3yE7csPDrU8kpFaf5VzByRQ4jVc1XZvT2IkR26D3IHia8eMKXaMEaiQQVo6e2XtaMOr+NJiEa/EjULQHxI5lAbA9PmbtGNzHvQ8MwPMaKp8u1dvJtZV/ilORx/4L5B7FmsMOqEGeMRnar2hgBBSoE/1fZ5u8vR2HjCtQ7s3KtCeD18hUo3BF0Ib8tZCoMY1cJ12GfLhuMY5oT0gJ2Eu0BdRhU/sxo14SUxxglAFd+k5tS9iyWYfTmlKE6eU4LfEVrApcv/Or6ztQwxU6VJvBU5UVlZLNwonSwAAXQf4FERgeF/mq6pJzGXKzJSUq/5M+hB0y/zUT4W1OZGmQvLBNSGf3l+Y=
  template:
    metadata:
      name: ghcr-secret-shellbin
      namespace: shellbin
    type: kubernetes.io/dockerconfigjson
