---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: shellbin
spec:
  encryptedData:
    .dockerconfigjson: AgBLFZDzZHsB16fjy29oLOLZK5GHeZZIq7qM4M0Pwy65fMYolBhmV57P+vLoh+Rq7WBi3HLG2W1yadaWH2Fy39jEmOK5picl2WJyK+xZXkcs2QKDw0cIAgOb4Cwzum1w7lCtXvsf19Z+W50xbdvoI8AMD7sV1RhctkWrIUhGkB1Z58txzzofnSS1i0ruTS9Dh9JaJyPJm5wX6zI/99a+ovDys8ZlLb8fiCysV6mEB3YiDpFxMrqZ53H/vTNtAV9O3IEBmS/VBb0akuZ0pZYdOh8WagjCwtPkGcDnYzeyywY7FtLmV5EV4XT7iQwA+giI8QfhLDEKR4qCBglPABKLQq6KVHxqhUcCM3Zw5CUWDDXlGqXrfNCFQS3P30MT0Kdk/SFPIP7KMSOttRzi+bT3sZAtX44qInTZQBBayjK+cBBgjmuspJNBGRHRlojf31rltNTodx41PMJ0DvT/WPD497g/RWFFurEps7YWyU2rxMiBhf2AsrVt03tkry42NMLhud9B7t0SyLss/kg1iNCJ3YD4fGR3yuARQkts2ia28Py0NDfgmqS+ndA5Tq/Asx+t8V1e3QbHb/tvEXD6dUEx5e5eTxj/3oq4fSRAy3l8EhrM5ec3SgJ9qdF9wIFCR5bOaTOuJnaxSc8/ApuRrTc9owFxMynf+6gWW4+44Bu8DVVHbK634R5tr6WqGQZPiKxvTDB57ulSSd1drBeYjNTqWdZT7bGWDpe7nlHMqsfbG358Z4EmfPvf4yq4diL97T+T1Q0yB8cFBrX8bhmVxYzCQo2ajXSob/vvHJfnqXyd40xjiH8Wv3HaKRjI5qQIW6V9vhBVYmLuIqV/vcsXLtWEL3I5kPz2mtz2Yp13lqMf2MMUdPU=
  template:
    metadata:
      name: ghcr-secret
      namespace: shellbin
    type: kubernetes.io/dockerconfigjson
