# points to a directory containing misc cluster configuration files
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-config/apps/cluster-yaml
    repoURL: git@github.com:england2/cluster-repo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      # prune: true: automatically prune resources resources that have been removed from the Git repo,
      prune: true
      # selfHeal: false: will not automatically correct resources that deviate from the definition
      # stored in the repo, i.e manual changes made with kubectl will persist, and not be 'healed'
      # away to restore the git-repo state
      selfHeal: false
