---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: ghcr-test
spec:
  encryptedData:
    .dockerconfigjson: AgBYQRXJJrjjnU+NWSai7VQgmLCmYArZ5BrazO8Q5x1dVcpxcKfJ2RiHSbExvagIVpPn3Rzgk7+agS6SO3rer+lhYGeDZvlQhriqt1GYsbork5l/ktX9jkv98b0l1wLDS3tWiFdRBuL47N6jO4NLzCgU+ylROZEwrNaCn/6Cj1bU3HzGJsNX02rnKVIxe+ANl6dYlboDdf3SVS76NulFK1eDlZaLj0JQ26SW61ycVq0RqWReXmuavQd39AkBreFgUV/gSSCk82YLPdflmukSZFHWDzMFbIt+Ful7ug2yfYlFeP9AfMCbTplQb23Pf5XpKB9TFsbT2Za7LSqj7Is9Bs53On3AIcV8uLePB4ud5RUiXONoYXny9QwpzjNL0T/4dPDDB0T9fB0BeI2uGw7PsjmwEFfgkr/dJBGJy86qjiapunDPuyob/xl8SeDk+2JjTi3Au7Lun8uA6gbMMRPcDkxJf/s2ojQn1+2oIiiyqyML54lxljXYjbaH//obOPAK/q6laP8X9+x4ntM9VI5c/wg0KZ6Bs4/16q7l0pzaaT1zxTXNT23s8QUqeGFfk/z5FlHu0Lv9U+QuIJe6vfJsr0Qf23UceT+n9C7pv1D26JnXSDPPnvnYITvw7iRRNuM8ip2oX1TFZrhKnptWzb8joHffiKVPP7jkn72tU8mFKc9Beyi/DHr0qrVCNFKrpw+DQoy0ZRlU9WHOL+gggvclCwJ609BkrrEq6jHcwnTK0e5DEpnFmk+dTb2ZWB+NhJIcp2L4ZzaTh5BqEmjc8LnQ8hW8hi/19K54Nf0/QmA0tHeiQ5dvIhLpefvlD3iSaMhVYAL9i4B2h13fHUrcKTJGSMzkz8m11EP8QT44t3XAT60ZSBTYhAbphnIQlD9azjWOYs68Q2wnlANV16BvD8KEk69+2vrruZZOWxOWwyYesTweA+bckNaVseIkXvpPEHNr0JljYzx+Be+eDiHAu8KNILV1Jgi6+bwp1e0CjaBg3QtAXt+4qBp2EQVGm6/964sKPlbW+loF/cVNUri6qCIQFaVuhA23Sm/pmubKWw==
  template:
    metadata:
      name: ghcr-secret
      namespace: ghcr-test
    type: kubernetes.io/dockerconfigjson
